### ISSUE TITLE
problem module swig

### ISSUE THREAD

**Issue by vanhoteen** [drmpeg/gr-dvbs#2]
Hi friends, I have a problem that generates me, I have ubuntu 16.04

 python ./dvbs_tx.py
Traceback (most recent call last):
  File "./dvbs_tx.py", line 31, in <module>
    import dvbs
  File "/usr/local/lib/python2.7/dist-packages/dvbs/__init__.py", line 45, in <module>
    from dvbs_swig import *
ImportError: No module named dvbs_swig

Can you help me

**Comment by drmpeg** [comment]
How did you install GNU Radio? You have to install gr-dvbs into the same directory that you installed GNU Radio.

If you used apt-get to install, then GNU Radio is in /usr. To install gr-dvbs into /usr, you have to set an install prefix with cmake. Like so:

cmake -DCMAKE_INSTALL_PREFIX=/usr

**Comment by vanhoteen** [comment]
thanks, I was lost, I have the gnuradio in / etc I don't know if it's normal, just install as the manual says .Thanks for responding so quickly
